spring:
  application:
    name: POST-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/postdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8089
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitBreaker:
    instances:
      commentBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 6000 # milliseconds
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
